### PR TITLE
Add input addon styles

### PR DESCRIPTION
**Pull request by tobyndockerill**

### CODE REVIEW

**Comment by blaknite** [comment]
Pleas add a description of expected behaviour to your PR.

**Comment by tobyndockerill** [comment]
This commit adds the ability to have input addons ([similar to Bootstrap](https://getbootstrap.com/components/#input-groups)).

**Comment by blaknite** [comment]
Just to confirm, is `.input-group` an existing Pure CSS class? From my understanding Pure has a `.pure-group` which groups inputs vertically or a `.pure-control-group` which is for grouping inputs and labels. Perhaps rename this to `.addon-group` for to remove that confusion and follow through to the subclasses.

Just keep in mind that the aim here is not to replicate bootstrap, but to add the "must haves" that Pure doesn't have. In this case I think this is a worthy addition. Let's make sure the CSS is as unopinionated as possible. Set up a test html page that includes Pure, and this gem's CSS to ensure it's compatible in stock form. Remove anything that was to match the admin theme we are working on and move it to the admin CSS.

Concept is sound otherwise.

**Comment by blaknite** [comment]
Oh and I just noticed the `display: table-cell;` on all inputs. I will have to test for any regressions.

**Comment by tobyndockerill** [comment]
All inputs (whether they have addons or not) will need a wrapper element, currently called `.input-group`. This element has a style of `display: table` to allow the addons to wrap and size properly. 

This may be a change better suited to the admin theme itself as it requires specific markup.

**Comment by blaknite** [comment]
Ahh ok, yeah that's quite a breaking change.

A better option would be to put the `display: table-cell;` on inputs inside the `.input-group` which is then renamed to `.addon-group`. This removes the regression and allows us to add this to the reset CSS.

**Comment by tobyndockerill** [comment]
Doing this may affect the styling of the input addons. Currently the wrapper element is `display: table;` then any inputs and addons are `display: table-cell;`, allowing them to resize nicely.

**Pull request merged**
